import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { AmortizationSummary, CalculationResults, PropertyData, formatCurrency } from "./calculations";

const NAVY = [13, 22, 38] as [number, number, number];
const TEAL = [0, 190, 165] as [number, number, number];
const WHITE = [255, 255, 255] as [number, number, number];
const LIGHT_GRAY = [245, 247, 250] as [number, number, number];
const MID_GRAY = [160, 172, 190] as [number, number, number];
const DARK_GRAY = [55, 65, 81] as [number, number, number];
const OFF_WHITE = [248, 250, 252] as [number, number, number];

const SIGNAL_FG: Record<string, [number, number, number]> = {
  Hold:      [22, 163, 74],
  Refinance: [37, 99, 235],
  Optimize:  [202, 138, 4],
  Sell:      [220, 38, 38],
};
const SIGNAL_BG: Record<string, [number, number, number]> = {
  Hold:      [220, 252, 231],
  Refinance: [219, 234, 254],
  Optimize:  [254, 249, 195],
  Sell:      [254, 226, 226],
};
const GREEN = [22, 163, 74] as [number, number, number];
const RED   = [220, 38, 38]  as [number, number, number];

function fmt(v: number) { return `${v.toFixed(1)}%`; }
function fmtScore(v: number) { return `${v.toFixed(1)} / 2.0`; }
function compact(v: number): string {
  if (Math.abs(v) >= 1_000_000) return `$${(v / 1_000_000).toFixed(2)}M`;
  if (Math.abs(v) >= 1_000) return `$${(v / 1_000).toFixed(0)}K`;
  return formatCurrency(v);
}

const AMBER = [202, 138, 4] as [number, number, number];
const EMERALD = [5, 150, 105] as [number, number, number];
const BLUE_TEXT = [37, 99, 235] as [number, number, number];
const ROSE = [220, 38, 38] as [number, number, number];

function drawHeader(doc: jsPDF, subtitle: string, rightLabel: string) {
  const W = doc.internal.pageSize.getWidth();
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, W, 36, "F");
  doc.setFillColor(...TEAL);
  doc.rect(0, 34, W, 2.5, "F");

  // Logo
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...WHITE);
  doc.text("Property", 14, 17);
  const pw = doc.getTextWidth("Property");
  doc.setTextColor(...TEAL);
  doc.text("AI", 14 + pw + 1, 17);

  // Right side
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...WHITE);
  const rw = doc.getTextWidth(rightLabel);
  doc.text(rightLabel, W - 14 - rw, 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...MID_GRAY);
  doc.text(subtitle, 14, 26);

  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const dw = doc.getTextWidth(date);
  doc.text(date, W - 14 - dw, 26);
}

function drawFooter(doc: jsPDF) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  doc.setFillColor(...NAVY);
  doc.rect(0, H - 12, W, 12, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6);
  doc.setTextColor(...MID_GRAY);
  doc.text("Generated by PropertyAI  •  For informational purposes only. Not financial advice.", 14, H - 4.5);
  const pg = String((doc as any).internal.getCurrentPageInfo().pageNumber);
  doc.text("Page " + pg, W - 14 - doc.getTextWidth("Page " + pg), H - 4.5);
}

function sectionLabel(doc: jsPDF, text: string, y: number): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...TEAL);
  doc.text(text.toUpperCase(), 14, y);
  doc.setFillColor(...TEAL);
  doc.rect(14, y + 1, doc.internal.pageSize.getWidth() - 28, 0.4, "F");
  return y + 6;
}

function drawSignalBanner(doc: jsPDF, signal: string, description: string, y: number): number {
  const W = doc.internal.pageSize.getWidth();
  const fg = SIGNAL_FG[signal] ?? DARK_GRAY;
  const bg = SIGNAL_BG[signal] ?? LIGHT_GRAY;

  doc.setFillColor(...bg);
  doc.roundedRect(14, y, W - 28, 20, 3, 3, "F");
  doc.setDrawColor(...fg);
  doc.setLineWidth(0.4);
  doc.roundedRect(14, y, W - 28, 20, 3, 3, "S");

  doc.setFillColor(...fg);
  doc.roundedRect(14, y, 38, 20, 3, 3, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...WHITE);
  const sw = doc.getTextWidth(signal.toUpperCase());
  doc.text(signal.toUpperCase(), 14 + (38 - sw) / 2, y + 12.5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...DARK_GRAY);
  doc.text(description, 58, y + 12.5);

  return y + 26;
}

function drawMetricsGrid(
  doc: jsPDF,
  items: { label: string; value: string; sub?: string; color?: [number, number, number] }[],
  y: number,
  cols = 2
): number {
  const W = doc.internal.pageSize.getWidth();
  const gap = 4;
  const colW = (W - 28 - (cols - 1) * gap) / cols;
  const cellH = 18;

  items.forEach((item, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const cx = 14 + col * (colW + gap);
    const cy = y + row * (cellH + gap);

    doc.setFillColor(...LIGHT_GRAY);
    doc.roundedRect(cx, cy, colW, cellH, 2, 2, "F");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(6);
    doc.setTextColor(...MID_GRAY);
    doc.text(item.label.toUpperCase(), cx + 5, cy + 5.5);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...(item.color ?? DARK_GRAY));
    doc.text(item.value, cx + 5, cy + 13.5);

    if (item.sub) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(6);
      doc.setTextColor(...MID_GRAY);
      const sw = doc.getTextWidth(item.sub);
      doc.text(item.sub, cx + colW - 5 - sw, cy + 13.5);
    }
  });

  const rows = Math.ceil(items.length / cols);
  return y + rows * (cellH + gap) + 2;
}

export function exportSinglePropertyPdf(
  propertyName: string,
  data: PropertyData,
  results: CalculationResults,
  amortization?: AmortizationSummary
) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  drawHeader(doc, "Asset Evaluation Report", propertyName);

  let y = 46;

  y = sectionLabel(doc, "Strategy Signal", y);
  y = drawSignalBanner(doc, results.strategySignal, results.strategyDescription, y);

  y = sectionLabel(doc, "Cash Flow", y);
  y = drawMetricsGrid(doc, [
    {
      label: "Monthly Cash Flow",
      value: formatCurrency(results.monthlyCashFlow),
      sub: `${formatCurrency(results.monthlyExpenses)} total expenses`,
      color: results.monthlyCashFlow >= 0 ? GREEN : RED,
    },
    {
      label: "Annual Cash Flow",
      value: formatCurrency(results.annualCashFlow),
      color: results.annualCashFlow >= 0 ? GREEN : RED,
    },
  ], y);

  y = sectionLabel(doc, "Equity & Exit Value", y);
  y = drawMetricsGrid(doc, [
    {
      label: "Available Equity",
      value: formatCurrency(results.availableEquity),
      sub: `${fmt(results.equityStrengthPercent)} equity strength`,
    },
    {
      label: "Cash If Sold Today",
      value: formatCurrency(results.estimatedCashIfSoldToday),
      sub: `-${formatCurrency(results.estimatedSellingCosts)} selling costs`,
    },
  ], y);

  y = sectionLabel(doc, "Performance", y);
  y = drawMetricsGrid(doc, [
    { label: "Equity Strength", value: fmt(results.equityStrengthPercent) },
    { label: "Capital Efficiency", value: fmt(results.capitalEfficiencyPercent) },
    { label: "Property Health Score", value: fmtScore(results.propertyHealthScore) },
  ], y, 3);

  y = sectionLabel(doc, "Property Inputs", y);

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [["Parameter", "Value"]],
    body: [
      ["Current Market Value",     formatCurrency(data.currentValue)],
      ["Original Purchase Price",  formatCurrency(data.purchasePrice)],
      ["Outstanding Mortgage",     formatCurrency(data.mortgageBalance)],
      ["Mortgage Interest Rate",   `${data.interestRate}%`],
      ["Monthly Rental Income",    formatCurrency(data.rentalIncome)],
      ["Monthly Mortgage Payment", formatCurrency(data.mortgagePayment)],
      ["Monthly Property Tax",     formatCurrency(data.propertyTax)],
      ["Monthly Insurance",        formatCurrency(data.insurance)],
      ["Monthly Maintenance",      formatCurrency(data.maintenance)],
      ["HOA / Other Fees",         formatCurrency(data.hoa)],
      ["Estimated Selling Costs",  `${data.sellingCostsPercent}%`],
      ["Annual Appreciation Rate", `${data.appreciationRatePercent}%`],
    ],
    styles: { fontSize: 8, cellPadding: 2.5, textColor: DARK_GRAY },
    headStyles: { fillColor: NAVY, textColor: WHITE, fontStyle: "bold", fontSize: 7.5 },
    alternateRowStyles: { fillColor: OFF_WHITE },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } },
  });

  drawFooter(doc);

  // ── Amortization page ──────────────────────────────────────────────────────
  if (amortization && amortization.rows.length > 0) {
    doc.addPage();
    drawHeader(doc, "Mortgage Amortization Schedule", propertyName);

    let ay = 46;

    // Summary stats
    ay = sectionLabel(doc, "Amortization Summary", ay);

    const payoffLabel = amortization.paysOff
      ? amortization.payoffYears > 0
        ? `${amortization.payoffYears}y ${amortization.payoffMonths}m`
        : `${amortization.payoffMonths} months`
      : "> 30 years";

    const lastRow = amortization.rows[amortization.rows.length - 1];

    ay = drawMetricsGrid(doc, [
      {
        label: "Payoff Timeline",
        value: payoffLabel,
        sub: amortization.paysOff ? "until mortgage-free" : "payment too low",
        color: TEAL,
      },
      {
        label: "Total Interest Paid",
        value: compact(amortization.totalInterestPaid),
        sub: "over life of loan",
        color: AMBER,
      },
      {
        label: "1st Month: Interest",
        value: formatCurrency(amortization.firstMonthInterest),
        sub: `of ${formatCurrency(data.mortgagePayment)} payment`,
        color: ROSE,
      },
      {
        label: "1st Month: Principal",
        value: formatCurrency(amortization.firstMonthPrincipal),
        sub: `${((amortization.firstMonthPrincipal / data.mortgagePayment) * 100).toFixed(1)}% of payment`,
        color: EMERALD,
      },
      {
        label: "Total Principal Paid",
        value: compact(amortization.totalPrincipalPaid),
        color: BLUE_TEXT,
      },
      {
        label: "Equity at Payoff",
        value: compact(lastRow.totalEquity),
        sub: "incl. appreciation",
        color: GREEN,
      },
    ], ay, 3);

    ay = sectionLabel(doc, "Year-by-Year Schedule", ay);

    const tableRows = amortization.rows.map((r) => [
      String(r.year),
      compact(r.remainingBalance),
      compact(r.yearlyPrincipal),
      compact(r.yearlyInterest),
      compact(r.cumulativePrincipal),
      compact(r.cumulativeInterest),
      compact(r.propertyValue),
      compact(r.totalEquity),
    ]);

    autoTable(doc, {
      startY: ay,
      margin: { left: 14, right: 14 },
      head: [["Year", "Balance", "Yr Principal", "Yr Interest", "Cum. Principal", "Cum. Interest", "Prop. Value", "Total Equity"]],
      body: tableRows,
      styles: { fontSize: 7, cellPadding: 2, textColor: DARK_GRAY, halign: "right" },
      headStyles: { fillColor: NAVY, textColor: WHITE, fontStyle: "bold", fontSize: 6.5 },
      alternateRowStyles: { fillColor: OFF_WHITE },
      columnStyles: {
        0: { halign: "center", fontStyle: "bold", cellWidth: 12 },
        1: { textColor: BLUE_TEXT as [number, number, number] },
        2: { textColor: EMERALD as [number, number, number] },
        3: { textColor: AMBER as [number, number, number] },
        5: { textColor: ROSE as [number, number, number] },
        7: { textColor: GREEN as [number, number, number], fontStyle: "bold" },
      },
    });

    drawFooter(doc);
  }

  doc.save(`PropertyAI_${propertyName.replace(/\s+/g, "_")}_Report.pdf`);
}

export function exportComparisonPdf(
  properties: Array<{ id: string; name: string; data: PropertyData; results: CalculationResults }>
) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();

  drawHeader(doc, "Portfolio Comparison Report", `${properties.length} Properties`);

  const top = properties.reduce((a, b) =>
    a.results.propertyHealthScore >= b.results.propertyHealthScore ? a : b
  );

  let y = 46;

  // Best property callout
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...DARK_GRAY);
  doc.text("Top performing asset:", 14, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...TEAL);
  doc.text(top.name, 14 + doc.getTextWidth("Top performing asset: "), y);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...MID_GRAY);
  doc.text(
    `Health Score ${fmtScore(top.results.propertyHealthScore)}  •  ${top.results.strategySignal}`,
    14 + doc.getTextWidth("Top performing asset: " + top.name + "  "),
    y
  );

  y += 8;

  // Numeric metric rows — find best values
  const metricDefs: { label: string; get: (r: CalculationResults) => number; fmt: (v: number) => string }[] = [
    { label: "Monthly Cash Flow",  get: r => r.monthlyCashFlow,        fmt: formatCurrency },
    { label: "Annual Cash Flow",   get: r => r.annualCashFlow,         fmt: formatCurrency },
    { label: "Available Equity",   get: r => r.availableEquity,        fmt: formatCurrency },
    { label: "Equity Strength",    get: r => r.equityStrengthPercent,  fmt: v => fmt(v) },
    { label: "Cash If Sold Today", get: r => r.estimatedCashIfSoldToday, fmt: formatCurrency },
    { label: "Capital Efficiency", get: r => r.capitalEfficiencyPercent, fmt: v => fmt(v) },
    { label: "Health Score",       get: r => r.propertyHealthScore,    fmt: fmtScore },
  ];

  const bestIdx: Record<string, number> = {};
  metricDefs.forEach(({ label, get }) => {
    const vals = properties.map(p => get(p.results));
    const max = Math.max(...vals);
    bestIdx[label] = vals.indexOf(max);
  });

  const tableBody: string[][] = [
    ...metricDefs.map(({ label, get, fmt: f }) =>
      [label, ...properties.map(p => f(get(p.results)))]
    ),
    ["Strategy Signal",  ...properties.map(p => p.results.strategySignal)],
    ["Current Value",    ...properties.map(p => formatCurrency(p.data.currentValue))],
    ["Purchase Price",   ...properties.map(p => formatCurrency(p.data.purchasePrice))],
    ["Mortgage Balance", ...properties.map(p => formatCurrency(p.data.mortgageBalance))],
    ["Interest Rate",    ...properties.map(p => `${p.data.interestRate}%`)],
    ["Monthly Rent",     ...properties.map(p => formatCurrency(p.data.rentalIncome))],
    ["Total Expenses",   ...properties.map(p => formatCurrency(p.results.monthlyExpenses))],
  ];

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [["Metric", ...properties.map(p => p.name)]],
    body: tableBody,
    styles: { fontSize: 8, cellPadding: 2.5, textColor: DARK_GRAY },
    headStyles: { fillColor: NAVY, textColor: WHITE, fontStyle: "bold", fontSize: 7.5 },
    alternateRowStyles: { fillColor: OFF_WHITE },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 44 } },
    didParseCell(data) {
      if (data.section !== "body") return;
      const rawRow = data.row.raw as string[];
      const rowLabel = String(rawRow[0]);
      const colIdx = data.column.index - 1;
      if (colIdx < 0) return;

      const cashFlowRows = ["Monthly Cash Flow", "Annual Cash Flow"];
      if (cashFlowRows.includes(rowLabel)) {
        const p = properties[colIdx];
        if (p) {
          const val = rowLabel === "Monthly Cash Flow"
            ? p.results.monthlyCashFlow
            : p.results.annualCashFlow;
          data.cell.styles.textColor = val >= 0 ? GREEN : RED;
        }
      }

      if (metricDefs.some(m => m.label === rowLabel)) {
        if (bestIdx[rowLabel] === colIdx && properties.length > 1) {
          data.cell.styles.fontStyle = "bold";
          data.cell.styles.textColor = GREEN;
        }
      }

      if (rowLabel === "Strategy Signal") {
        const sig = properties[colIdx]?.results.strategySignal;
        if (sig && SIGNAL_FG[sig]) data.cell.styles.textColor = SIGNAL_FG[sig];
      }
    },
  });

  drawFooter(doc);
  doc.save(`PropertyAI_Portfolio_Comparison_${properties.length}_Properties.pdf`);
}
